language: node_js
os:
  - osx
  - linux
  - windows
node_js:
  - "14"
  - "13"
  - "12"
script: "NODE_PATH=. ./node_modules/.bin/mocha -R spec test/*"
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: "kraivit.m@ku.th"
  api_key: "L-72OD438P4SCHuyz_wk6g"
notifications:
